default_platform(:android)

platform :android do

  desc "Upload APK to Firebase App Distribution"
  lane :firebase_release do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    firebase_app_distribution(
      apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "baselalkhateeb45@gmail.com",
      release_notes: "New production release using fastlane"
    )
  end

end