name: Android App Distribution

on:
  push:
    branches:
      - development

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install Bundler locally
        run: |
          gem install bundler -v 2.6.9 --user-install
          export PATH="$HOME/.gem/ruby/$(ls $HOME/.gem/ruby)/bin:$PATH"

      - name: Install Fastlane gems
        run: |
          cd android
          bundle _2.6.9_ install --path vendor/bundle

      - name: Run Fastlane
        working-directory: android
        env:
          FIRBASE_CLI_TOKEN: ${{ secrets.FIRBASE_CLI_TOKEN }}
        run: bundle _2.6.9_ exec fastlane firebase_release